# Generated by Django 6.0 on 2025-12-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('HUMANITIES', 'Humanities'), ('NONE', 'None')], default='NONE', max_length=15),
        ),
        migrations.AddField(
            model_name='subject',
            name='form_level',
            field=models.CharField(choices=[('ALL', 'All Forms'), ('F1', 'Form 1'), ('F2', 'Form 2'), ('F3', 'Form 3'), ('F4', 'Form 4')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.CharField(choices=[('ALL', 'All Streams'), ('SCIENCE', 'Science Stream'), ('HUMANITIES', 'Humanities Stream'), ('JUNIOR', 'Junior Classes Only'), ('SENIOR', 'Senior Classes Only')], default='ALL', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.CharField(choices=[('F1', 'Form 1'), ('F2', 'Form 2'), ('F3S', 'Form 3 Science'), ('F3H', 'Form 3 Humanities'), ('F4S', 'Form 4 Science'), ('F4H', 'Form 4 Humanities')], default='F1', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='forms_responsible',
            field=models.CharField(blank=True, help_text='Forms this teacher is responsible for (e.g., "F3S,F4H" or "ALL")', max_length=50, null=True),
        ),
    ]
